project: 
  type: website

title: "Erasmus MC ~ Programming Café"
theme: code-cafe.scss

website: 
  navbar: 
    logo: assets/img/logo.png
    right: 
      - href: about.qmd
      - href: meetups/index.qmd
      - href: resources/resources.qmd
      - icon: github
        aria-label: EMC coding café GitHub repo
        href: https://github.com/SereDef/EMC-coding-cafe